spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simple-note;
    username: 1234
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      defer-datasource-initialization: true
    hibernate:
      #ddl-auto: create
#       show_sql: true
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 80