spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simplenote?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

    #url: jdbc:mysql://hs89omhh81rfahi2:f3h0yurt7e5prr8i@l6glqt8gsx37y4hs.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/juk5oqyxien7ntw0
    username: root #hs89omhh81rfahi2
    password: rkdtmdrn123 #f3h0yurt7e5prr8i
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 80